-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2026-05-07
-- Autor: José Luiz Limeira
-- =====================================================

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2026-05-07'),
    'V0033',
    'Ajustes para Nova tabela de Classificações Tributárias alterada em 15/04/2026.'
);

-------------------------------------------------------------------------------------------------
-- Descrição:
-- Ajustes na tabela FUNDAMENTACAO_CLASSIFICACAO, TRATAMENTO_CLASSIFICACAO e MUNICIPIO.
-----------------------------------------------------------------------------------------------

INSERT INTO FUNDAMENTACAO_CLASSIFICACAO(FDCL_ID,FDCL_CLTR_ID,FDCL_FDLG_ID,FDCL_INICIO_VIGENCIA,FDCL_FIM_VIGENCIA) VALUES(185,185,185,'2026-01-01',NULL);
INSERT INTO FUNDAMENTACAO_CLASSIFICACAO(FDCL_ID,FDCL_CLTR_ID,FDCL_FDLG_ID,FDCL_INICIO_VIGENCIA,FDCL_FIM_VIGENCIA) VALUES(186,186,186,'2026-01-01',NULL);
INSERT INTO TRATAMENTO_CLASSIFICACAO(TRCL_ID,TRCL_CLTR_ID,TRCL_TRTR_ID,TRCL_INICIO_VIGENCIA,TRCL_FIM_VIGENCIA) VALUES(185,185,3,'2026-01-01',NULL);
INSERT INTO TRATAMENTO_CLASSIFICACAO(TRCL_ID,TRCL_CLTR_ID,TRCL_TRTR_ID,TRCL_INICIO_VIGENCIA,TRCL_FIM_VIGENCIA) VALUES(186,186,9,'2026-01-01',NULL);
INSERT INTO MUNICIPIO(MUNI_CD,MUNI_UF_CD,MUNI_NOME) VALUES(5101837,51,'Boa Esperança do Norte');

