-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2026-05-04
-- Autor: José Luiz Limeira
-- =====================================================

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2026-05-04'),
    'V0032',
    'Nova tabela de Classificações Tributárias alterada em 15/04/2026.'
);

-------------------------------------------------------------------------------------------------
-- Descrição:
-- Carga na tabela CLASSIFICACAO_TRIBUTARIA e nas tabelas relacionadas.
-----------------------------------------------------------------------------------------------

UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='90111', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=2;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='92401', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=9;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DESCRICAO='Situação de emergência de saúde pública reconhecida pelo Poder público', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=17;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91561', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=27;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=31;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='93081', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=36;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91581', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=37;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='92611', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=38;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=39;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='92811' WHERE CLTR_ID=59;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91271', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=63;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='94871', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=67;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91721', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=120;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91722', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=121;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DESCRICAO='Tributação monofásica com responsabilidade de retenção de tributos por terceiros', CLTR_ANEXO='91723', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=122;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91724', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=123;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91725', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=124;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91726', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=125;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DESCRICAO='Documento com informações de fornecimento de serviços de planos de assistência à saúde elencados no art. 234 da Lei Complementar nº214, de 2025', CLTR_ANEXO='92341', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=132;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='92361', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=133;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='92431', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=134;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=136;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='90111', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=137;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_ANEXO='91811', CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=174;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_IND_GMONOPADRAO=0, CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=183;
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_DATA_ATUALIZACAO='2026-04-15' WHERE CLTR_ID=184;
INSERT INTO CLASSIFICACAO_TRIBUTARIA(CLTR_ID,CLTR_CD,CLTR_DESCRICAO,CLTR_MEMORIA_CALCULO,CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_CBS,CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_IBS,CLTR_IN_CREDITO_PRESUMIDO_FORNECEDOR,CLTR_IN_CREDITO_PRESUMIDO_ADQUIRENTE,CLTR_SITR_ID,CLTR_TMES_ID,CLTR_TIPO_ALIQUOTA,CLTR_CREDITO_OPERACAO_ANTECEDENTE,CLTR_NOMENCLATURA,CLTR_INICIO_VIGENCIA,CLTR_FIM_VIGENCIA,CLTR_IND_GCREDPRESOPER,CLTR_IND_GMONOPADRAO,CLTR_IND_GMONORETEN,CLTR_IND_GMONORET,CLTR_IND_GMONODIF,CLTR_IND_GESTORNOCRED,CLTR_ANEXO,CLTR_DATA_ATUALIZACAO) VALUES(185,'000005','Operação com EAC destinado à mistura com gasolina A, mas com saída do biocombustível com destinação diversa','Operação de consumo com enquadramento legal em [norma], tributada conforme [tratamento]. A base de cálculo utilizada é de R$ [base_calculo], com alíquota de [aliquota_ad_valorem]%.',1,1,0,0,1,NULL,'Padrão','Manutenção','NCM','2026-01-01',NULL,0,0,0,0,0,0,NULL,'2026-04-15');
INSERT INTO CLASSIFICACAO_TRIBUTARIA(CLTR_ID,CLTR_CD,CLTR_DESCRICAO,CLTR_MEMORIA_CALCULO,CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_CBS,CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_IBS,CLTR_IN_CREDITO_PRESUMIDO_FORNECEDOR,CLTR_IN_CREDITO_PRESUMIDO_ADQUIRENTE,CLTR_SITR_ID,CLTR_TMES_ID,CLTR_TIPO_ALIQUOTA,CLTR_CREDITO_OPERACAO_ANTECEDENTE,CLTR_NOMENCLATURA,CLTR_INICIO_VIGENCIA,CLTR_FIM_VIGENCIA,CLTR_IND_GCREDPRESOPER,CLTR_IND_GMONOPADRAO,CLTR_IND_GMONORETEN,CLTR_IND_GMONORET,CLTR_IND_GMONODIF,CLTR_IND_GESTORNOCRED,CLTR_ANEXO,CLTR_DATA_ATUALIZACAO) VALUES(186,'200054','Fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS','Operação de consumo com enquadramento legal em [norma], tributada conforme [tratamento]. A base de cálculo utilizada é de R$ [base_calculo], com alíquota de zero.',0,0,0,0,4,NULL,'Padrão','Manutenção','NCM','2026-01-01',NULL,0,0,0,0,0,1,NULL,'2026-04-15');
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_TEXTO='Art. 271. As sociedades cooperativas poderão optar por regime específico do IBS e da CBS no qual ficam reduzidas a zero as alíquotas do IBS e da CBS incidentes na operação em que: \nI - o associado fornece bem ou serviço à cooperativa de que participa; e \nII - a cooperativa fornece bem ou serviço a associado sujeito ao regime regular do IBS e da CBS.\n§ 1º O disposto no caput deste artigo aplica-se também:\nI - às operações realizadas entre cooperativas singulares, centrais, federações, confederações e às originárias dos seus respectivos bancos cooperativos de que as cooperativas participam;' WHERE FDLG_ID=31;
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_TEXTO='Art. 172. O IBS e a CBS incidirão uma única vez sobre as operações, ainda que iniciadas no exterior, com os seguintes combustíveis, qualquer que seja a sua finalidade.', FDLG_TEXTO_CURTO='Art. 172' WHERE FDLG_ID=120;
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_TEXTO_CURTO='Art. 234' WHERE FDLG_ID=132;
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_TEXTO_CURTO='Art. 60' WHERE FDLG_ID=184;
INSERT INTO FUNDAMENTACAO_LEGAL(FDLG_ID,FDLG_TEXTO,FDLG_TEXTO_CURTO,FDLG_REFERENCIA_NORMATIVA,FDLG_INICIO_VIGENCIA,FDLG_FIM_VIGENCIA) VALUES(185,'Art. 179. Nas operações com EAC:\nI - o adquirente de EAC destinado à mistura com gasolina A que realizar a saída dos biocombustíveis com destinação diversa fica obrigado a recolher o IBS e a CBS incidentes sobre o biocombustível;','Art. 179, I','LIVRO I \n\nDO IMPOSTO SOBRE BENS E SERVIÇOS (IBS) E DA CONTRIBUIÇÃO SOCIAL SOBRE BENS E SERVIÇOS (CBS) \n\nTÍTULO I \n\nDAS NORMAS GERAIS DO IBS E DA CBS \n\nCAPÍTULO II\n\nDO IBS E DA CBS SOBRE OPERAÇÕES COM BENS E SERVIÇOS\n\nSeção IV\n\nDo Local da Operação','2026-01-01',NULL);
INSERT INTO FUNDAMENTACAO_LEGAL(FDLG_ID,FDLG_TEXTO,FDLG_TEXTO_CURTO,FDLG_REFERENCIA_NORMATIVA,FDLG_INICIO_VIGENCIA,FDLG_FIM_VIGENCIA) VALUES(186,'Art. 271. As sociedades cooperativas poderão optar por regime específico do IBS e da CBS no qual ficam reduzidas a zero as alíquotas do IBS e da CBS incidentes na operação em que: \n§ 1º O disposto no caput deste artigo aplica-se também:\nII - à operação de fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS, desde que anulados os créditos por ela apropriados referentes ao bem fornecido.','Art. 271, § 1º, II','LIVRO I \n\nDO IMPOSTO SOBRE BENS E SERVIÇOS (IBS) E DA CONTRIBUIÇÃO SOCIAL SOBRE BENS E SERVIÇOS (CBS) \n\nTÍTULO IV\n\nDOS REGIMES DIFERENCIADOS DO IBS E DA CBS\n\nCAPÍTULO IV\n\nDA REDUÇÃO A ZERO DAS ALÍQUOTAS DO IBS E DA CBS\n\nSeção II\n\nDos Dispositivos Médicos','2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(463,185,2,0.0,'2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(464,185,3,0.0,'2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(465,185,4,0.0,'2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(466,186,2,100.0,'2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(467,186,3,100.0,'2026-01-01',NULL);
INSERT INTO PERCENTUAL_REDUCAO(PERE_ID,PERE_CLTR_ID,PERE_TBTO_ID,PERE_VALOR,PERE_INICIO_VIGENCIA,PERE_FIM_VIGENCIA) VALUES(468,186,4,100.0,'2026-01-01',NULL);
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=71;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=260;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=263;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=265;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=267;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=269;
DELETE FROM TIPO_DFE_CLASSIFICACAO WHERE TDCL_ID=290;
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(345,31,9,'2026-01-01',NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(346,184,5,'2026-01-01',NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(347,185,2,'2026-01-01',NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(348,186,2,'2026-01-01',NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(349,186,3,'2026-01-01',NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO(TDCL_ID,TDCL_CLTR_ID,TDCL_TPDF_ID,TDCL_INICIO_VIGENCIA,TDCL_FIM_VIGENCIA) VALUES(350,186,10,'2026-01-01',NULL);
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_IN_EXIGE_GRUPO_DESONERACAO=1 WHERE TRTR_ID=41;

