-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2026-07-07
-- Autor: Leonardo Gargitter
-- =====================================================

-- *****************************************************************************************
-- ************** É OBRIGATÓRIO INCLUIR O REGISTRO NA TABELA VERSAO_BASE_DADO **************
-- *****************************************************************************************

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2026-07-07'),
    'V0041',
    'Adiciona a coluna IOIC_CD_LOCAL_INCIDENCIA a tabela INDICADOR_OPERACAO_IBS_CBS.'
);

-- -----------------------------------------------------------------------------------------------
-- Descrição:
-- Adiciona a coluna IOIC_CD_LOCAL_INCIDENCIA a tabela INDICADOR_OPERACAO_IBS_CBS.
-- -----------------------------------------------------------------------------------------------

DELETE FROM INDICADOR_OPERACAO_IBS_CBS;

ALTER TABLE INDICADOR_OPERACAO_IBS_CBS 
ADD COLUMN IOIC_CD_LOCAL_INCIDENCIA INTEGER;

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (1, '020101', 'Localidade do Imóvel', '2026-01-01', '2026-08-31', 'Operação com bem imóvel, bem imaterial, inclusive direito,  relacionada a bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (2, '020201', 'Localidade do Imóvel', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (3, '020301', 'Localidade do Imóvel', '2026-01-01', '2026-08-31', 'Serviço de administração e intermediação de bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (4, '030101', 'Estabelecimento do Prestador/Fornecedor', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 5, 3);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (5, '030102', 'Endereço do Tomador/Adquirente', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 2, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (6, '030103', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 3, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (7, '030104', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 1, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (8, '040101', 'Local do Evento', '2026-01-01', '2026-08-31', 'Serviço de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres', 13, 5);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (9, '050101', 'Estabelecimento do Prestador/Fornecedor', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre bem móvel material', 5, 3);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (10, '050102', 'Endereço do Tomador/Adquirente', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre bem móvel material', 2, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (11, '050103', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre bem móvel material', 3, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (12, '050104', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviço prestado fisicamente sobre bem móvel material', 1, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (13, '050201', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviços portuários', 6, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (14, '060101', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviço de transporte de passageiros', 9, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (15, '070101', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviço de transporte de carga', 4, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (16, '070102', 'Local da Prestação', '2026-01-01', '2026-08-31', 'Serviço de transporte de carga', 8, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (17, '080101', 'Localização do Trecho', '2026-01-01', '2026-08-31', 'Serviço de exploração de via', 7, 7);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (18, '100101', 'Endereço do Tomador/Adquirente', '2026-01-01', '2026-08-31', 'Cessão de espaço para prestação de serviços publicitários, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (19, '100102', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Cessão de espaço para prestação de serviços publicitários, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (20, '100201', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Cessão de espaço para prestação de serviços publicitários, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (21, '100301', 'Endereço do Tomador/Adquirente', '2026-01-01', '2026-08-31', 'Demais serviços, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (22, '100302', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Demais serviços, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (23, '100401', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Demais serviços, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (24, '100501', 'Endereço do Tomador/Adquirente', '2026-01-01', '2026-08-31', 'Demais bens móveis imateriais, inclusive direitos, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (25, '100502', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Demais bens móveis imateriais, inclusive direitos, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (26, '100601', 'Endereço do Destinatário', '2026-01-01', '2026-08-31', 'Demais bens móveis imateriais, inclusive direitos, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (27, '010101', 'Estabelecimento do Prestador/Fornecedor', '2026-09-01', NULL, 'Bem Móvel Material', 15, 3);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (28, '010102', 'Local da Prestação', '2026-09-01', NULL, 'Bem Móvel Material', 16, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (29, '010103', 'Endereço do Destinatário', '2026-09-01', NULL, 'Bem Móvel Material', 17, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (30, '010104', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Bem Móvel Material', 18, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (31, '010105', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Bem Móvel Material', 19, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (32, '010106', 'Endereço do Tomador/Adquirente', '2026-09-01', NULL, 'Bem Móvel Material', 20, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (33, '010201', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Aquisição de veículo automotor terrestre, aquático ou aéreo', 21, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (34, '010202', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Aquisição de veículo automotor em licitação promovida pelo poder público de bem apreendido ou abandonado ou leilão judicial', 21, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (35, '020101', 'Localidade do Imóvel', '2026-09-01', NULL, 'Operação com bem imóvel, bem imaterial, inclusive direito, relacionada a bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (36, '020201', 'Localidade do Imóvel', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (37, '020202', 'Localidade do Imóvel', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (38, '020301', 'Localidade do Imóvel', '2026-09-01', NULL, 'Serviço de administração e intermediação de bem imóvel', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (39, '020401', 'Localidade do Imóvel', '2026-09-01', NULL, 'Serviços de locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza', 14, 6);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (40, '030101', 'Estabelecimento do Prestador/Fornecedor', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 5, 3);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (41, '030102', 'Local da Prestação', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física', 2, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (42, '040101', 'Local do Evento', '2026-09-01', NULL, 'Serviço de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres', 13, 5);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (43, '050101', 'Estabelecimento do Prestador/Fornecedor', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre bem móvel material', 5, 3);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (44, '050102', 'Local da Prestação', '2026-09-01', NULL, 'Serviço prestado fisicamente sobre bem móvel material', 2, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (45, '050201', 'Local da Prestação', '2026-09-01', NULL, 'Serviços portuários', 6, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (46, '060101', 'Local da Prestação', '2026-09-01', NULL, 'Serviço de transporte de passageiros', 9, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (47, '070101', 'Local da Prestação', '2026-09-01', NULL, 'Serviço de transporte de carga', 4, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (48, '070102', 'Local da Prestação', '2026-09-01', NULL, 'Serviço de transporte de carga', 8, 4);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (49, '080101', 'Localização do Trecho', '2026-09-01', NULL, 'Serviço de exploração de via', 7, 7);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (50, '090101', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Serviço de telefonia fixa e demais serviços de comunicação prestados por meio de cabos, fios, fibras e meios similares', 22, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (51, '090102', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Serviço de telefonia fixa e demais serviços de comunicação prestados por meio de cabos, fios, fibras e meios similares', 23, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (52, '100101', 'Endereço do Tomador/Adquirente', '2026-09-01', NULL, 'Cessão de espaço para prestação de serviços publicitários, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (53, '100102', 'Endereço do Destinatário', '2026-09-01', NULL, 'Cessão de espaço para prestação de serviços publicitários, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (54, '100201', 'Endereço do Destinatário', '2026-09-01', NULL, 'Cessão de espaço para prestação de serviços publicitários, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (55, '100301', 'Endereço do Tomador/Adquirente', '2026-09-01', NULL, 'Demais serviços, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (56, '100302', 'Endereço do Destinatário', '2026-09-01', NULL, 'Demais serviços, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (57, '100401', 'Endereço do Destinatário', '2026-09-01', NULL, 'Demais serviços, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (58, '100501', 'Endereço do Tomador/Adquirente', '2026-09-01', NULL, 'Demais bens, em operações onerosas', 11, 2);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (59, '100502', 'Endereço do Destinatário', '2026-09-01', NULL, 'Demais bens, em operações onerosas', 10, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (60, '100601', 'Endereço do Destinatário', '2026-09-01', NULL, 'Demais bens, em operações não onerosas', 12, 1);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (61, '110101', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Operações com abastecimento de água, gás canalizado e energia elétrica', 24, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (62, '110201', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Operações com abastecimento de água, gás canalizado e energia elétrica', 25, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (63, '120101', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Nas aquisições de energia elétrica realizadas de forma multilateral', 26, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (64, '130101', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Operações de transporte dutoviário de gás natural', 27, NULL);

INSERT INTO INDICADOR_OPERACAO_IBS_CBS (IOIC_ID, IOIC_CD, IOIC_LOCAL_INCIDENCIA, IOIC_INICIO_VIGENCIA, IOIC_FIM_VIGENCIA, IOIC_TIPO_OPERACAO, IOIC_CD_LOCAL_FORNECIMENTO_DFE, IOIC_CD_LOCAL_INCIDENCIA)
VALUES (65, '130201', 'NÃO DEFINIDO', '2026-09-01', NULL, 'Operações de transporte dutoviário de gás natural', 28, NULL);
