-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2026-07-22
-- Autor: José Luiz Limeira
-- =====================================================

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
   datetime('2026-07-22'),
   'V0045',
   'Criação das tabelas relacionadas com ATOR.'
);

-------------------------------------------------------------------------------------------------
-- Descrição:
-- Criação das tabelas relacionadas com ATOR..
-------------------------------------------------------------------------------------------------

CREATE TABLE GRUPO_ATOR (
    GRAT_ID INTEGER NOT NULL,
    GRAT_DESCRICAO TEXT NOT NULL,
    GRAT_INICIO_VIGENCIA TEXT NOT NULL,
    GRAT_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (GRAT_FIM_VIGENCIA IS NULL OR GRAT_FIM_VIGENCIA >= GRAT_INICIO_VIGENCIA),
    GRAT_ORDEM INTEGER NOT NULL,
    PRIMARY KEY(GRAT_ID)
);

CREATE TABLE ATOR (
    ATOR_ID INTEGER NOT NULL,
    ATOR_DESCRICAO TEXT NOT NULL,
    ATOR_GRAT_ID INTEGER NOT NULL,
    ATOR_INICIO_VIGENCIA TEXT NOT NULL,
    ATOR_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ATOR_FIM_VIGENCIA IS NULL OR ATOR_FIM_VIGENCIA >= ATOR_INICIO_VIGENCIA),
    ATOR_ORDEM INTEGER NOT NULL,
    PRIMARY KEY(ATOR_ID),
    FOREIGN KEY(ATOR_GRAT_ID) REFERENCES GRUPO_ATOR(GRAT_ID)
);

CREATE TABLE ATOR_CLASSIFICACAO (
    ATCL_ID INTEGER NOT NULL,
    ATCL_CLTR_ID INTEGER NOT NULL,
    ATCL_ATOR_ID INTEGER NOT NULL,
    ATCL_IN_PAPEL TEXT NOT NULL CHECK (ATCL_IN_PAPEL IN ('Fornecedor','Adquirente')),
    ATCL_INICIO_VIGENCIA TEXT NOT NULL,
    ATCL_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ATCL_FIM_VIGENCIA IS NULL OR ATCL_FIM_VIGENCIA >= ATCL_INICIO_VIGENCIA),
    PRIMARY KEY(ATCL_ID),
    FOREIGN KEY(ATCL_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(ATCL_ATOR_ID) REFERENCES ATOR(ATOR_ID)
);

CREATE TABLE ATOR_CLASSIFICACAO_FUNDAMENTACAO (
    ATCF_ID INTEGER NOT NULL,
    ATCF_FDLG_ID INTEGER NOT NULL,
    ATCF_ATCL_ID INTEGER NOT NULL,
    ATCF_INICIO_VIGENCIA TEXT NOT NULL,
    ATCF_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ATCF_FIM_VIGENCIA IS NULL OR ATCF_FIM_VIGENCIA >= ATCF_INICIO_VIGENCIA),
    PRIMARY KEY(ATCF_ID),
    FOREIGN KEY(ATCF_FDLG_ID) REFERENCES FUNDAMENTACAO_LEGAL(FDLG_ID),
    FOREIGN KEY(ATCF_ATCL_ID) REFERENCES ATOR_CLASSIFICACAO(ATCL_ID)
);

CREATE INDEX IDX_ATOR_GRAT_ID ON ATOR(ATOR_GRAT_ID);
CREATE INDEX IDX_ATCL_ATOR_ID ON ATOR_CLASSIFICACAO(ATCL_ATOR_ID);
CREATE INDEX IDX_ATCL_CLTR_ID ON ATOR_CLASSIFICACAO(ATCL_CLTR_ID);
CREATE INDEX IDX_ATCF_ATCL_ID ON ATOR_CLASSIFICACAO_FUNDAMENTACAO(ATCF_ATCL_ID);
CREATE INDEX IDX_ATCF_FDLG_ID ON ATOR_CLASSIFICACAO_FUNDAMENTACAO(ATCF_FDLG_ID);

CREATE INDEX IDX_ATOR_INICIO_VIGENCIA ON ATOR(ATOR_INICIO_VIGENCIA);
CREATE INDEX IDX_ATOR_FIM_VIGENCIA ON ATOR(ATOR_FIM_VIGENCIA);
CREATE INDEX IDX_ATCL_INICIO_VIGENCIA ON ATOR_CLASSIFICACAO(ATCL_INICIO_VIGENCIA);
CREATE INDEX IDX_ATCL_FIM_VIGENCIA ON ATOR_CLASSIFICACAO(ATCL_FIM_VIGENCIA);
CREATE INDEX IDX_ATCF_INICIO_VIGENCIA ON ATOR_CLASSIFICACAO_FUNDAMENTACAO(ATCF_INICIO_VIGENCIA);
CREATE INDEX IDX_ATCF_FIM_VIGENCIA ON ATOR_CLASSIFICACAO_FUNDAMENTACAO(ATCF_FIM_VIGENCIA);
CREATE INDEX IDX_GRAT_INICIO_VIGENCIA ON GRUPO_ATOR(GRAT_INICIO_VIGENCIA);
CREATE INDEX IDX_GRAT_FIM_VIGENCIA ON GRUPO_ATOR(GRAT_FIM_VIGENCIA);

