-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2026-09-02
-- Autor: Luis Augusto
-- =====================================================

-- *****************************************************************************************
-- ************** É OBRIGATÓRIO INCLUIR O REGISTRO NA TABELA VERSAO_BASE_DADO **************
-- *****************************************************************************************

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2026-09-02'),
    'V0056',
    'Mais ajustes para resolver problemas de alíquotas não definidas em lei.'
);

-- =======================================================================
-- Mais ajustes para resolver problemas de alíquotas não definidas em lei.
-- =======================================================================

-- Novo tratamento para 221001: alíquota fictícia (não definida em lei),
-- calculada ad valorem sobre a base de cálculo.
-- TRTR_IN_POSSUI_AJUSTE = 0 para que 221001 continue calculável.

INSERT INTO TRATAMENTO_TRIBUTARIO
(TRTR_ID, TRTR_DESCRICAO, TRTR_EXPRESSAO_ALIQUOTA, TRTR_EXPRESSAO_ALIQUOTA_EFETIVA, TRTR_EXPRESSAO_BASE_CALCULO, TRTR_EXPRESSAO_TRIBUTO_CALCULADO, TRTR_EXPRESSAO_TRIBUTO_DEVIDO, TRTR_EXPRESSAO_PERCENTUAL_DIFERIMENTO, TRTR_EXPRESSAO_VALOR_DIFERIMENTO, TRTR_IN_INCOMPATIVEL_COM_SUSPENSAO, TRTR_IN_EXIGE_GRUPO_DESONERACAO, TRTR_IN_POSSUI_PERCENTUAL_REDUCAO, TRTR_IN_POSSUI_AJUSTE, TRTR_IN_POSSUI_REDUTOR, TRTR_INICIO_VIGENCIA, TRTR_FIM_VIGENCIA, TRTR_IN_POSSUI_MONOFASIA)
VALUES(43, 'Alíquota fixa fictícia', 'aliquota', 'aliquota*(1-percentualReducao)*(1-pRedutorCompraGov/100)', 'baseCalculoInformada-impostoSeletivoInformado+impostoSeletivoCalculado', 'baseCalculo*aliquotaEfetiva', 'tributoCalculado', NULL, NULL, 0, 0, 1, 0, 0, '2026-01-01', NULL, 0);

-- Reaponta 221001 (CLTR_ID=67) do tratamento 37 (Alíquota fixa proporcional,
-- desabilitado mais abaixo) para o novo tratamento 43.

UPDATE TRATAMENTO_CLASSIFICACAO
SET TRCL_TRTR_ID=43
WHERE TRCL_ID=67;

-- Estabelecendo novas alíquotas para os serviços financeiros:
--
-- 010001
-- 010002

UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.9, AADV_TBTO_ID=2, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=5
WHERE AADV_ID=39;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.1, AADV_TBTO_ID=3, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=5
WHERE AADV_ID=40;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.0, AADV_TBTO_ID=4, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=5
WHERE AADV_ID=41;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.9, AADV_TBTO_ID=2, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=6
WHERE AADV_ID=45;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.1, AADV_TBTO_ID=3, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=6
WHERE AADV_ID=46;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.0, AADV_TBTO_ID=4, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=6
WHERE AADV_ID=47;

-- Estabelecendo as alíquotas de 221001 (CLTR_ID=67):
-- 3,65% repartido (90% CBS, 10% IBS UF, 0% IBS Mun)

UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=3.285, AADV_TBTO_ID=2, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=67
WHERE AADV_ID=60;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.365, AADV_TBTO_ID=3, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=67
WHERE AADV_ID=61;
UPDATE ALIQUOTA_AD_VALOREM
SET AADV_VALOR=0.0, AADV_TBTO_ID=4, AADV_INICIO_VIGENCIA='2026-01-01', AADV_FIM_VIGENCIA='2026-12-31', AADV_CLTR_ID=67
WHERE AADV_ID=62;

-- Desabilitando (TRTR_IN_POSSUI_AJUSTE=1 => NAO_IMPLEMENTADO):
--
-- 220001 e 221002 => tratamento 34
-- 220002 e 221003 => tratamento 35
-- 220003 e 221004 => tratamento 36
--
-- O tratamento 37 (Alíquota fixa proporcional) também é desabilitado:
-- após o reaponte de 221001, nenhuma classificação o utiliza.

UPDATE TRATAMENTO_TRIBUTARIO
SET TRTR_IN_POSSUI_AJUSTE=1
WHERE TRTR_ID=34;

UPDATE TRATAMENTO_TRIBUTARIO
SET TRTR_IN_POSSUI_AJUSTE=1
WHERE TRTR_ID=35;

UPDATE TRATAMENTO_TRIBUTARIO
SET TRTR_IN_POSSUI_AJUSTE=1
WHERE TRTR_ID=36;

UPDATE TRATAMENTO_TRIBUTARIO
SET TRTR_IN_POSSUI_AJUSTE=1
WHERE TRTR_ID=37;

-- Deletando as alíquotas dos que estão sendo desabilitados:
--
-- 220001 => 51, 52, 53
-- 220002 => 54, 55, 56
-- 220003 => 57, 58, 59
-- 221002 => 63, 64, 65
-- 221003 => 66, 67, 68
-- 221004 => 69, 70, 71
--
-- As alíquotas 60, 61 e 62 (221001) são mantidas.

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=51;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=52;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=53;

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=54;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=55;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=56;

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=57;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=58;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=59;

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=63;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=64;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=65;

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=66;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=67;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=68;

DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=69;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=70;
DELETE FROM ALIQUOTA_AD_VALOREM
WHERE AADV_ID=71;
