-- =====================================================
-- CALLBACK FLYWAY: afterMigrate.sql
-- Verificações e otimizações pós-migração
-- Gerado em: 2025-09-24
-- =====================================================

-- =====================================================
-- SEÇÃO 0: ATUALIZAÇÃO DE VIGÊNCIA RETROATIVA
-- Objetivo: Atualizar datas de início de vigência de 2026-01-01 para 2025-01-01
-- em todas as tabelas que possuem colunas com sufixo '_inicio_vigencia'.

-- Descomente e execute o script abaixo sempre que houver atualização de estrutura (criaçao de tabela nova) e atualize os updates para que todas as tabelas estejam cobertas.
-- Essas atualizações devem ser removidas antes de entrar em producao. 
-- =====================================================
-- SELECT
--     'UPDATE ' || m.name || ' SET ' || p.name || ' = ''2025-01-01'' WHERE ' || p.name || ' = ''2026-01-01'';'
-- FROM sqlite_master m
-- JOIN pragma_table_info(m.name) p
-- WHERE m.type = 'table'
--   AND p.name LIKE '%inicio_vigencia'
--   ORDER BY m.name ASC;
-- =====================================================

UPDATE AJUSTE SET AJST_INICIO_VIGENCIA = '2025-01-01' WHERE AJST_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM SET AARE_INICIO_VIGENCIA = '2025-01-01' WHERE AARE_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM_PRODUTO SET AARP_INICIO_VIGENCIA = '2025-01-01' WHERE AARP_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM_SERVICO SET AARS_INICIO_VIGENCIA = '2025-01-01' WHERE AARS_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM SET AADV_INICIO_VIGENCIA = '2025-01-01' WHERE AADV_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM_PRODUTO SET AAVP_INICIO_VIGENCIA = '2025-01-01' WHERE AAVP_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM_SERVICO SET AAVS_INICIO_VIGENCIA = '2025-01-01' WHERE AAVS_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_PADRAO SET ALPA_INICIO_VIGENCIA = '2025-01-01' WHERE ALPA_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_REFERENCIA SET ALRE_INICIO_VIGENCIA = '2025-01-01' WHERE ALRE_INICIO_VIGENCIA = '2026-01-01';
UPDATE ANEXO SET ANXO_INICIO_VIGENCIA = '2025-01-01' WHERE ANXO_INICIO_VIGENCIA = '2026-01-01';
UPDATE APROPRIACAO_CREDITO_ADQUIRENTE SET APCA_INICIO_VIGENCIA = '2025-01-01' WHERE APCA_INICIO_VIGENCIA = '2026-01-01';
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_INICIO_VIGENCIA = '2025-01-01' WHERE CLTR_INICIO_VIGENCIA = '2026-01-01';
UPDATE CLASSIF_NBS_INDOP_LC SET CNIL_INICIO_VIGENCIA = '2025-01-01' WHERE CNIL_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_REM_PRODUTO SET EARP_INICIO_VIGENCIA = '2025-01-01' WHERE EARP_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_REM_SERVICO SET EARS_INICIO_VIGENCIA = '2025-01-01' WHERE EARS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_VALOREM_PRODUTO SET EAVP_INICIO_VIGENCIA = '2025-01-01' WHERE EAVP_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_VALOREM_SERVICO SET EAVS_INICIO_VIGENCIA = '2025-01-01' WHERE EAVS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_NBS_APLICAVEL SET ENBS_INICIO_VIGENCIA = '2025-01-01' WHERE ENBS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_NCM_APLICAVEL SET ENCM_INICIO_VIGENCIA = '2025-01-01' WHERE ENCM_INICIO_VIGENCIA = '2026-01-01';
UPDATE FUNDAMENTACAO_CLASSIFICACAO SET FDCL_INICIO_VIGENCIA = '2025-01-01' WHERE FDCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_INICIO_VIGENCIA = '2025-01-01' WHERE FDLG_INICIO_VIGENCIA = '2026-01-01';
UPDATE INDICADOR_OPERACAO_IBS_CBS SET IOIC_INICIO_VIGENCIA = '2025-01-01' WHERE IOIC_INICIO_VIGENCIA = '2026-01-01';
UPDATE LISTA_SERVICOS_LC_116 SET LSLC_INICIO_VIGENCIA = '2025-01-01' WHERE LSLC_INICIO_VIGENCIA = '2026-01-01';
UPDATE NBS SET NBS_INICIO_VIGENCIA = '2025-01-01' WHERE NBS_INICIO_VIGENCIA = '2026-01-01';
UPDATE NBS_APLICAVEL SET NBSA_INICIO_VIGENCIA = '2025-01-01' WHERE NBSA_INICIO_VIGENCIA = '2026-01-01';
UPDATE NCM SET NCM_INICIO_VIGENCIA = '2025-01-01' WHERE NCM_INICIO_VIGENCIA = '2026-01-01';
UPDATE NCM_APLICAVEL SET NCMA_INICIO_VIGENCIA = '2025-01-01' WHERE NCMA_INICIO_VIGENCIA = '2026-01-01';
UPDATE PERCENTUAL_REDUCAO SET PERE_INICIO_VIGENCIA = '2025-01-01' WHERE PERE_INICIO_VIGENCIA = '2026-01-01';
UPDATE REDUTOR SET RDTO_INICIO_VIGENCIA = '2025-01-01' WHERE RDTO_INICIO_VIGENCIA = '2026-01-01';
UPDATE REDUTOR_COMPRA_GOVERNAMENTAL SET RCGO_INICIO_VIGENCIA = '2025-01-01' WHERE RCGO_INICIO_VIGENCIA = '2026-01-01';
UPDATE SITUACAO_TRIBUTARIA SET SITR_INICIO_VIGENCIA = '2025-01-01' WHERE SITR_INICIO_VIGENCIA = '2026-01-01';
UPDATE TIPO_DFE SET TPDF_INICIO_VIGENCIA = '2025-01-01' WHERE TPDF_INICIO_VIGENCIA = '2026-01-01';
UPDATE TIPO_DFE_CLASSIFICACAO SET TDCL_INICIO_VIGENCIA = '2025-01-01' WHERE TDCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE TOMADOR_ESPECIFICO SET TMES_INICIO_VIGENCIA = '2025-01-01' WHERE TMES_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRANSFERENCIA_CBS_ENTE_GOV SET TCEG_INICIO_VIGENCIA = '2025-01-01' WHERE TCEG_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRATAMENTO_CLASSIFICACAO SET TRCL_INICIO_VIGENCIA = '2025-01-01' WHERE TRCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_INICIO_VIGENCIA = '2025-01-01' WHERE TRTR_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRIBUTO SET TBTO_INICIO_VIGENCIA = '2025-01-01' WHERE TBTO_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRIBUTO_SITUACAO_TRIBUTARIA SET TRST_INICIO_VIGENCIA = '2025-01-01' WHERE TRST_INICIO_VIGENCIA = '2026-01-01';
UPDATE UNIDADE_MEDIDA SET UNMD_INICIO_VIGENCIA = '2025-01-01' WHERE UNMD_INICIO_VIGENCIA = '2026-01-01';
-- =====================================================
-- Alterar vigência de 2027 para 2026 de itens relacionados com Tributo 1-Imposto Seletivo
-- Data: 2027-08-28
-- Autor: José Luiz Limeira
-- =====================================================
-- TRIBUTO  (1 registro(s) afetado(s))
-- Caminho: TRIBUTO — direto (TBTO_ID = 1)

UPDATE TRIBUTO
SET    TBTO_INICIO_VIGENCIA = '2026-01-01'
WHERE  TBTO_ID = 1
  AND  TBTO_INICIO_VIGENCIA = '2027-01-01';

-- ALIQUOTA_AD_REM  (2 registro(s) afetado(s))
-- Caminho: ALIQUOTA_AD_REM — via AARE_TBTO_ID
UPDATE ALIQUOTA_AD_REM
SET    AARE_INICIO_VIGENCIA = '2026-01-01'
WHERE  AARE_TBTO_ID = 1
  AND  AARE_INICIO_VIGENCIA = '2027-01-01';

-- ALIQUOTA_AD_VALOREM  (13 registro(s) afetado(s))
-- Caminho: ALIQUOTA_AD_VALOREM — via AADV_TBTO_ID
UPDATE ALIQUOTA_AD_VALOREM
SET    AADV_INICIO_VIGENCIA = '2026-01-01'
WHERE  AADV_TBTO_ID = 1
  AND  AADV_INICIO_VIGENCIA = '2027-01-01';

-- ALIQUOTA_REFERENCIA  (0 registro(s) afetado(s))
-- Caminho: ALIQUOTA_REFERENCIA — via ALRE_TBTO_ID
UPDATE ALIQUOTA_REFERENCIA
SET    ALRE_INICIO_VIGENCIA = '2026-01-01'
WHERE  ALRE_TBTO_ID = 1
  AND  ALRE_INICIO_VIGENCIA = '2027-01-01';

-- TRIBUTO_SITUACAO_TRIBUTARIA  (7 registro(s) afetado(s))
-- Caminho: TRIBUTO_SITUACAO_TRIBUTARIA — via TRST_TBTO_ID
UPDATE TRIBUTO_SITUACAO_TRIBUTARIA
SET    TRST_INICIO_VIGENCIA = '2026-01-01'
WHERE  TRST_TBTO_ID = 1
  AND  TRST_INICIO_VIGENCIA = '2027-01-01';

-- ALIQUOTA_AD_REM_PRODUTO  (3 registro(s) afetado(s))
-- Caminho: ALIQUOTA_AD_REM_PRODUTO — via AARP_AARE_ID → ALIQUOTA_AD_REM
UPDATE ALIQUOTA_AD_REM_PRODUTO
SET    AARP_INICIO_VIGENCIA = '2026-01-01'
WHERE  AARP_ID IN (
    SELECT p.AARP_ID
    FROM   ALIQUOTA_AD_REM_PRODUTO p
           INNER JOIN ALIQUOTA_AD_REM a ON a.AARE_ID = p.AARP_AARE_ID
    WHERE  a.AARE_TBTO_ID = 1
      AND  p.AARP_INICIO_VIGENCIA = '2027-01-01'
);

-- ALIQUOTA_AD_VALOREM_PRODUTO  (101 registro(s) afetado(s))
-- Caminho: ALIQUOTA_AD_VALOREM_PRODUTO — via AAVP_AADV_ID → ALIQUOTA_AD_VALOREM
UPDATE ALIQUOTA_AD_VALOREM_PRODUTO
SET    AAVP_INICIO_VIGENCIA = '2026-01-01'
WHERE  AAVP_ID IN (
    SELECT p.AAVP_ID
    FROM   ALIQUOTA_AD_VALOREM_PRODUTO p
           INNER JOIN ALIQUOTA_AD_VALOREM a ON a.AADV_ID = p.AAVP_AADV_ID
    WHERE  a.AADV_TBTO_ID = 1
      AND  p.AAVP_INICIO_VIGENCIA = '2027-01-01'
);

-- ALIQUOTA_AD_VALOREM_SERVICO  (1 registro(s) afetado(s))
-- Caminho: ALIQUOTA_AD_VALOREM_SERVICO — via AAVS_AADV_ID → ALIQUOTA_AD_VALOREM
UPDATE ALIQUOTA_AD_VALOREM_SERVICO
SET    AAVS_INICIO_VIGENCIA = '2026-01-01'
WHERE  AAVS_ID IN (
    SELECT s.AAVS_ID
    FROM   ALIQUOTA_AD_VALOREM_SERVICO s
           INNER JOIN ALIQUOTA_AD_VALOREM a ON a.AADV_ID = s.AAVS_AADV_ID
    WHERE  a.AADV_TBTO_ID = 1
      AND  s.AAVS_INICIO_VIGENCIA = '2027-01-01'
);

-- EXCECAO_AD_VALOREM_PRODUTO  (1 registro(s) afetado(s))
-- Caminho: EXCECAO_AD_VALOREM_PRODUTO — via EAVP_AAVP_ID → ALIQUOTA_AD_VALOREM_PRODUTO → ALIQUOTA_AD_VALOREM
UPDATE EXCECAO_AD_VALOREM_PRODUTO
SET    EAVP_INICIO_VIGENCIA = '2026-01-01'
WHERE  EAVP_ID IN (
    SELECT e.EAVP_ID
    FROM   EXCECAO_AD_VALOREM_PRODUTO e
           INNER JOIN ALIQUOTA_AD_VALOREM_PRODUTO p ON p.AAVP_ID = e.EAVP_AAVP_ID
           INNER JOIN ALIQUOTA_AD_VALOREM a        ON a.AADV_ID  = p.AAVP_AADV_ID
    WHERE  a.AADV_TBTO_ID = 1
      AND  e.EAVP_INICIO_VIGENCIA = '2027-01-01'
);

-- SITUACAO_TRIBUTARIA  (7 registro(s) afetado(s))
-- Caminho: SITUACAO_TRIBUTARIA — via TRST_SITR_ID (TRIBUTO_SITUACAO_TRIBUTARIA)
UPDATE SITUACAO_TRIBUTARIA
SET    SITR_INICIO_VIGENCIA = '2026-01-01'
WHERE  SITR_ID IN (
    SELECT DISTINCT s.SITR_ID
    FROM   SITUACAO_TRIBUTARIA s
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA t ON t.TRST_SITR_ID = s.SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  s.SITR_INICIO_VIGENCIA = '2027-01-01'
);

-- CLASSIFICACAO_TRIBUTARIA  (30 registro(s) afetado(s))
-- Caminho: CLASSIFICACAO_TRIBUTARIA — via CLTR_SITR_ID → SITUACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE CLASSIFICACAO_TRIBUTARIA
SET    CLTR_INICIO_VIGENCIA = '2026-01-01'
WHERE  CLTR_ID IN (
    SELECT DISTINCT c.CLTR_ID
    FROM   CLASSIFICACAO_TRIBUTARIA c
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA t ON t.TRST_SITR_ID = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  c.CLTR_INICIO_VIGENCIA = '2027-01-01'
);

-- FUNDAMENTACAO_CLASSIFICACAO  (30 registro(s) afetado(s))
-- Caminho: FUNDAMENTACAO_CLASSIFICACAO — via FDCL_CLTR_ID → CLASSIFICACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE FUNDAMENTACAO_CLASSIFICACAO
SET    FDCL_INICIO_VIGENCIA = '2026-01-01'
WHERE  FDCL_ID IN (
    SELECT DISTINCT f.FDCL_ID
    FROM   FUNDAMENTACAO_CLASSIFICACAO f
           INNER JOIN CLASSIFICACAO_TRIBUTARIA       c ON c.CLTR_ID      = f.FDCL_CLTR_ID
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA    t ON t.TRST_SITR_ID = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  f.FDCL_INICIO_VIGENCIA = '2027-01-01'
);

-- FUNDAMENTACAO_LEGAL  (30 registro(s) afetado(s))
-- Caminho: FUNDAMENTACAO_LEGAL — via FDCL_FDLG_ID → FUNDAMENTACAO_CLASSIFICACAO → CLASSIFICACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE FUNDAMENTACAO_LEGAL
SET    FDLG_INICIO_VIGENCIA = '2026-01-01'
WHERE  FDLG_ID IN (
    SELECT DISTINCT fl.FDLG_ID
    FROM   FUNDAMENTACAO_LEGAL fl
           INNER JOIN FUNDAMENTACAO_CLASSIFICACAO    f  ON f.FDCL_FDLG_ID  = fl.FDLG_ID
           INNER JOIN CLASSIFICACAO_TRIBUTARIA       c  ON c.CLTR_ID       = f.FDCL_CLTR_ID
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA    t  ON t.TRST_SITR_ID  = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  fl.FDLG_INICIO_VIGENCIA = '2027-01-01'
);

-- NBS_APLICAVEL  (6 registro(s) afetado(s))
-- Caminho: NBS_APLICAVEL — via NBSA_CLTR_ID → CLASSIFICACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE NBS_APLICAVEL
SET    NBSA_INICIO_VIGENCIA = '2026-01-01'
WHERE  NBSA_ID IN (
    SELECT DISTINCT n.NBSA_ID
    FROM   NBS_APLICAVEL n
           INNER JOIN CLASSIFICACAO_TRIBUTARIA       c ON c.CLTR_ID      = n.NBSA_CLTR_ID
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA    t ON t.TRST_SITR_ID = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  n.NBSA_INICIO_VIGENCIA = '2027-01-01'
);

-- NCM_APLICAVEL  (391 registro(s) afetado(s))
-- Caminho: NCM_APLICAVEL — via NCMA_CLTR_ID → CLASSIFICACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE NCM_APLICAVEL
SET    NCMA_INICIO_VIGENCIA = '2026-01-01'
WHERE  NCMA_ID IN (
    SELECT DISTINCT n.NCMA_ID
    FROM   NCM_APLICAVEL n
           INNER JOIN CLASSIFICACAO_TRIBUTARIA       c ON c.CLTR_ID      = n.NCMA_CLTR_ID
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA    t ON t.TRST_SITR_ID = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  n.NCMA_INICIO_VIGENCIA = '2027-01-01'
);

-- TRATAMENTO_CLASSIFICACAO  (30 registro(s) afetado(s))
-- Caminho: TRATAMENTO_CLASSIFICACAO — via TRCL_CLTR_ID → CLASSIFICACAO_TRIBUTARIA → TRIBUTO_SITUACAO_TRIBUTARIA
UPDATE TRATAMENTO_CLASSIFICACAO
SET    TRCL_INICIO_VIGENCIA = '2026-01-01'
WHERE  TRCL_ID IN (
    SELECT DISTINCT tr.TRCL_ID
    FROM   TRATAMENTO_CLASSIFICACAO tr
           INNER JOIN CLASSIFICACAO_TRIBUTARIA       c ON c.CLTR_ID      = tr.TRCL_CLTR_ID
           INNER JOIN TRIBUTO_SITUACAO_TRIBUTARIA    t ON t.TRST_SITR_ID = c.CLTR_SITR_ID
    WHERE  t.TRST_TBTO_ID = 1
      AND  tr.TRCL_INICIO_VIGENCIA = '2027-01-01'
);

-- Total de registros afetados: 653
--
--
--

CREATE INDEX IF NOT EXISTS idx_ajuste_vigencia ON AJUSTE (AJST_INICIO_VIGENCIA, AJST_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_rem_vigencia ON ALIQUOTA_AD_REM (AARE_INICIO_VIGENCIA, AARE_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_rem_produto_vigencia ON ALIQUOTA_AD_REM_PRODUTO (AARP_INICIO_VIGENCIA, AARP_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_rem_servico_vigencia ON ALIQUOTA_AD_REM_SERVICO (AARS_INICIO_VIGENCIA, AARS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_valorem_vigencia ON ALIQUOTA_AD_VALOREM (AADV_INICIO_VIGENCIA, AADV_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_valorem_produto_vigencia ON ALIQUOTA_AD_VALOREM_PRODUTO (AAVP_INICIO_VIGENCIA, AAVP_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_ad_valorem_servico_vigencia ON ALIQUOTA_AD_VALOREM_SERVICO (AAVS_INICIO_VIGENCIA, AAVS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_padrao_vigencia ON ALIQUOTA_PADRAO (ALPA_INICIO_VIGENCIA, ALPA_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_aliquota_referencia_vigencia ON ALIQUOTA_REFERENCIA (ALRE_INICIO_VIGENCIA, ALRE_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_anexo_vigencia ON ANEXO (ANXO_INICIO_VIGENCIA, ANXO_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_apropriacao_credito_adquirente_vigencia ON APROPRIACAO_CREDITO_ADQUIRENTE (APCA_INICIO_VIGENCIA, APCA_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_classificacao_tributaria_vigencia ON CLASSIFICACAO_TRIBUTARIA (CLTR_INICIO_VIGENCIA, CLTR_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_ad_rem_produto_vigencia ON EXCECAO_AD_REM_PRODUTO (EARP_INICIO_VIGENCIA, EARP_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_ad_rem_servico_vigencia ON EXCECAO_AD_REM_SERVICO (EARS_INICIO_VIGENCIA, EARS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_ad_valorem_produto_vigencia ON EXCECAO_AD_VALOREM_PRODUTO (EAVP_INICIO_VIGENCIA, EAVP_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_ad_valorem_servico_vigencia ON EXCECAO_AD_VALOREM_SERVICO (EAVS_INICIO_VIGENCIA, EAVS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_nbs_aplicavel_vigencia ON EXCECAO_NBS_APLICAVEL (ENBS_INICIO_VIGENCIA, ENBS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_excecao_ncm_aplicavel_vigencia ON EXCECAO_NCM_APLICAVEL (ENCM_INICIO_VIGENCIA, ENCM_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_fundamentacao_classificacao_vigencia ON FUNDAMENTACAO_CLASSIFICACAO (FDCL_INICIO_VIGENCIA, FDCL_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_fundamentacao_legal_vigencia ON FUNDAMENTACAO_LEGAL (FDLG_INICIO_VIGENCIA, FDLG_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_nbs_vigencia ON NBS (NBS_INICIO_VIGENCIA, NBS_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_nbs_aplicavel_vigencia ON NBS_APLICAVEL (NBSA_INICIO_VIGENCIA, NBSA_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_ncm_vigencia ON NCM (NCM_INICIO_VIGENCIA, NCM_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_ncm_aplicavel_vigencia ON NCM_APLICAVEL (NCMA_INICIO_VIGENCIA, NCMA_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_percentual_reducao_vigencia ON PERCENTUAL_REDUCAO (PERE_INICIO_VIGENCIA, PERE_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_redutor_vigencia ON REDUTOR (RDTO_INICIO_VIGENCIA, RDTO_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_situacao_tributaria_vigencia ON SITUACAO_TRIBUTARIA (SITR_INICIO_VIGENCIA, SITR_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tipo_dfe_vigencia ON TIPO_DFE (TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tipo_dfe_classificacao_vigencia ON TIPO_DFE_CLASSIFICACAO (TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tomador_especifico_vigencia ON TOMADOR_ESPECIFICO (TMES_INICIO_VIGENCIA, TMES_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tratamento_classificacao_vigencia ON TRATAMENTO_CLASSIFICACAO (TRCL_INICIO_VIGENCIA, TRCL_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tratamento_tributario_vigencia ON TRATAMENTO_TRIBUTARIO (TRTR_INICIO_VIGENCIA, TRTR_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tributo_vigencia ON TRIBUTO (TBTO_INICIO_VIGENCIA, TBTO_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_tributo_situacao_tributaria_vigencia ON TRIBUTO_SITUACAO_TRIBUTARIA (TRST_INICIO_VIGENCIA, TRST_FIM_VIGENCIA);
CREATE INDEX IF NOT EXISTS idx_unidade_medida_vigencia ON UNIDADE_MEDIDA (UNMD_INICIO_VIGENCIA, UNMD_FIM_VIGENCIA);


-- =====================================================
-- SEÇÃO 1: VERIFICAÇÕES DE INTEGRIDADE
-- =====================================================

-- Verifica integridade geral do banco
PRAGMA integrity_check;

-- Verifica consistência de chaves estrangeiras
PRAGMA foreign_key_check;

-- Verifica se foreign keys estão habilitadas
SELECT 
    CASE 
        WHEN foreign_keys = 1 THEN '✅ Foreign keys HABILITADAS'
        ELSE '❌ Foreign keys DESABILITADAS - PROBLEMA!'
    END as status_fk
FROM PRAGMA_foreign_keys();

-- =====================================================
-- SEÇÃO 2: ANÁLISE DE PERFORMANCE
-- =====================================================

-- Atualiza estatísticas para otimização de consultas
ANALYZE;

-- Executa otimizações automáticas
PRAGMA optimize;

-- Verifica tamanho das tabelas principais
SELECT 
    name as tabela,
    ROUND((
        SELECT COUNT(*) * 
        (SELECT AVG(length(sql)) FROM sqlite_master WHERE type='table' AND name=m.name)
        FROM sqlite_master WHERE type='table' AND name=m.name
    ) / 1024.0, 2) || ' KB' as tamanho_estimado
FROM sqlite_master m
WHERE type = 'table' 
AND name NOT LIKE 'sqlite_%'
AND name NOT LIKE 'flyway_%'
ORDER BY name;

-- =====================================================
-- FIM DAS VERIFICAÇÕES
-- =====================================================

-- Mensagem final
SELECT '🎉 Verificações pós-migração concluídas com sucesso!' as status_final;

-- =====================================================
-- CALLBACK afterMigrate.sql - CONCLUÍDO
-- =====================================================
